### ISSUE TITLE
Scanner View Controller continually called

### ISSUE THREAD

**Issue by allynl93** [mattrubin/Authenticator#105]
Downloaded the latest version and when I click the + button the QR reader view is continually called. E.g. the new view opens over and and over again. Can click cancel and get back to the main screen, but cannot add tokens via QR code or even manually. 

I've tried to workout what the issue is but I'm kind of new to coding and I just broke it even more. 

Using iPhone 6 with iOS 9.2.1.

**Comment by allynl93** [comment]
Update. So if I add a break point in RootViewContoller at case.scanner under:

extension RootViewController {
    func updateWithViewModel(viewModel: Root.ViewModel) {
        tokenListViewController.updateWithViewModel(viewModel.tokenList)

        switch viewModel.modal {
        case .None:
            dismissViewController()
        case .Scanner:

When I continue past the breakpoint the scanner is only presented once... It's as though something isn't being loaded or called in time. Without the breakpoint the app will eventually successfully display the QR code, but it does need to display the view lots of time. My record so car is 32 times.

**Comment by allynl93** [comment]
I have got round this a bit, probably not a very good way of fixing it at all... Like I say new to this. But all I did was add a variable to show that the view controller for the Scanner was already open once and then why you close the view controller it put the value back to the original. As such it only opens the scanner once... 

Probably very bad way of doing it tbh, but only thing I could think of...

**Comment by mattrubin** [comment]
Ah, good catch! That's what I get for running development builds in the simulator, and not on an actual device.

This bug is fixed in PR #107. The solution, as you discovered, was to check if the scanner was already visible when updating the root view model. Instead of adding a new variable to track this, I check the current view model and the type of the top view controller. (The same check was already being done for the entry and edit form modals.)
