### ISSUE TITLE
App Crashes when trying to manually add an entry

### ISSUE THREAD

**Issue by JoshuaCrewe** [mattrubin/authenticator#314]
I have an iPhone 5c on iOS 10.3.3 running version 2.1.1 of the authenticator app.

I have one entry which was added via the QR code which worked fine.

I am now trying to add a new entry manually. I click the + symbol in the bottom right which loads up the camera. I then click on the "new entry" button in the top right to manually add data. The screen goes black and the app quits.

I cannot update my iOS version as Apple do not support this device any more. I tried restarting my device and that did not fix the issue. I am not sure how to turn on crash reporting if I am honest.

Happy to provide any additional information needed 🥇

**Comment by JoshuaCrewe** [comment]
As a workaround I found https://stefansundin.github.io/2fa-qr/ which basically does the same thing.

**Comment by mattrubin** [comment]
@JoshuaCrewe I'm sorry to hear the app is crashing on you! I will try to reproduce this crash on a test device on my end, but the easiest way to track down the source of the crash would be to see a crash log from your phone.

If you go into the iOS "Settings" app, then scroll down and tap "Privacy", then scroll down and tap "Analytics", you should see a screen like the one below. (The naming and placement of items in the menus might be slightly different on iOS 10.3.3) To turn on crash reporting, you need to first enable the setting named "Share iPhone Analytics", and then turn on the setting labelled "Share with App Developers". This will let your phone automatically send me reports on future crashes.

To send me the crash reports that have already been generated (or if you don't want to turn on analytics sharing for some reason), tap into the "Analytics Data" section from this screen, then scroll until you find the crash reports with names beginning with "Authenticator" or "me.mattrubin.Authenticator". If you tap in to each crash log, you can then use the share button in the upper right to send it to authenticator@mattrubin.me.

I'll keep an eye out for incoming crash logs. Please let me know when you send them my way.

<img src="https://user-images.githubusercontent.com/532638/58024018-3fe86000-7adf-11e9-9b9b-c6d9f69807df.PNG" width="50%" />

**Comment by JoshuaCrewe** [comment]
Well I turned on Analytics sharing. The share button wasn't there in my interface. Would it be helpful to copy and paste the text content in an email ? We might loose the formatting. Can you access that file as an attachment?

**Comment by mattrubin** [comment]
@JoshuaCrewe: I have several crash reports that have been sent automatically via Apple, but if you can copy and paste your latest crash report into an email, it will be helpful for me to confirm that the crash you're experiencing is the same one as indicated by these other crash reports.

Also, if you are interested, I can then add your email address to the list of beta testers, so I can send you a TestFlight build. This would help me confirm that the new build is fixing your crash, and help you by getting you a fixed build several days faster than you would get it through the App Store.

**Comment by mattrubin** [comment]
Progress on tracking down this crash: So far, I have managed to reproduce a crash that resembles the one reported, on a device running iOS 9.3. This seems to be a Swift runtime bug: A struct is stored to a variable, and then when it is accessed, the app crashes with EXC_BAD_ACCESS. This happens when the app is built with Xcode 10.2.1 (Swift 5.0.1 compiler), but not when the app is build with Xcode 10.1 (Swift 4.2.1 compiler).

Update: This seems to be an issue specifically for 32-bit devices. Running the same problematic code in the simulator, it crashes with a memory error on an iPhone 4s and an iPhone 5, but seems to run fine on an iPhone 5s and above...

**Comment by JoshuaCrewe** [comment]
@mattrubin I sent over the crash report just now.

Add me to the beta, I'd like to help fix this bug, I can't help with the code so happy to help with the debugging. Use apple@joshuacrewe.co.uk as I have that set up with testflight already. Thanks!

**Comment by mattrubin** [comment]
I've done some more testing on an iPhone 5 running iOS 10.3.3 and an iPhone 5s running iOS 10.0.2. The app compiled with Xcode 10.2.1 runs fine on the 64-bit iPhone 5s, but crashes on the 32-bit iPhone 5. The exact same code compiled with Xcode 10.1 runs correctly on both devices.

@JoshuaCrewe I'm pushing a new TestFlight build using the previous version of Xcode, which should not exhibit the same crash. You should receive an email invite to test it shortly. Please let me know if it fixes the issue for you!

After reviewing the app analytics provided by Apple, it appears that 32-bit devices make up _at most_ 1.25% of all the devices that have run the app in the last 90 days (that don't have analytics reporting disabled). In the long term, if Apple does not fix the underlying bug, I might have to drop support for 32-bit devices, but for now using the slightly older Xcode should be a workable fix.

*If anyone else is encountering this or a similar crash, please email me at authenticator@mattrubin.me so that I can send you the beta build with the fix.*

**Comment by JoshuaCrewe** [comment]
@mattrubin I got the email and joined test flight. It lets me download Version 2.2.2 (2439) , is that the right build? I still get the same crash though with this installed. Will you get the crash report from this quicker via test flight ?

**Comment by mattrubin** [comment]
@JoshuaCrewe sorry for the confusion! I think you actually downloaded an older build. It looks like the new build (2448) got stuck in Apple's review process[1] overnight. It typically gets cleared in one business day, and I'll let you know when it's available to download.

[1] Apple insists on a manual human review of the first TestFlight build with each new version number, even though nothing has changed from the last build aside from one bug fix, and even though I could then send – without review – new TestFlight builds with the same version number that change anything I want. 🤷🏻‍♂️

**Comment by JoshuaCrewe** [comment]
OH ok. Thats fine. I will wait for the new build and test that.

Conversations about how Apple do things could fuel endless conversations I am sure.

**Comment by mattrubin** [comment]
@JoshuaCrewe The beta build is now available! Please let me know if it helps.

**Comment by JoshuaCrewe** [comment]
@mattrubin I got it. That has restored the manual entry functionality! 🎉

Thank you for spending the time looking in to and getting this working👍

Am I right in thinking what you have done is a work around and Apple need to fix something in Xcode compilation process?

**Comment by mattrubin** [comment]
@JoshuaCrewe I'm glad it's fixed the issue for you! Thanks for the detailed bug report and crash reports that helped me track this down.

You're correct that this is a workaround – I won't be able to use an old version of the compiler forever. When I have some time next week, I'm planning on reducing the crash down to a simpler example with which I can file a bug report with Apple.

**Comment by JoshuaCrewe** [comment]
@mattrubin if you need help with anything I am happy to do so. I am not optimistic about Apples response though :)
