### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by alfredonodo** [mattrubin/authenticator#401]
Hello,
I really appreciate your project, however it seems to have been abandoned since the last release was about 3 years ago. Is the project still alive? Do you have a roadmap?
Thank you

**Comment by id21-space-developer** [comment]
> Hello, I really appreciate your project, however it seems to have been abandoned since the last release was about 3 years ago. Is the project still alive? Do you have a roadmap? Thank you

Please go ahead with this project, everyone is praying for a backup of the keys to be able to manage within any platform at will it would be a dream for many people because I believe that there are people like me who have very important things connected to these keys safety, do not ignore please is important....

**Comment by id21-space-developer** [comment]
Please go ahead with this project, everyone is praying for a backup of the keys to be able to manage within any platform at will it would be a dream for many people because I believe that there are people like me who have very important things connected to these keys safety, do not ignore please is important....

**Comment by itspt1** [comment]
Hi @mattrubin 
This is an awesome simple app that a lot of people appreciate since it's open source. 
It'd be really kind of you if you could implement some sort of migration option.

I'm sure some would even consider a monetary compensation for your time and effort.

**Comment by mattrubin** [comment]
> it seems to have been abandoned since the last release was about 3 years ago. Is the project still alive?

While the project isn't abandoned – I still personally use that 3-year-old release without any issues – my time has been extremely limited, and the project has unfortunately been poorly maintained.

> Do you have a roadmap?

At this time, I can't commit to a roadmap that involves adding any features. However, I've recently started work on a small maintenance update to test and re-release the app with the latest iOS SDK. If you are interested in testing the updated version before its public release, you can join the beta here: https://testflight.apple.com/join/J8Zrq5bJ
